
wandb: Network error resolved after 0:00:08.514126, resuming normal operation.
{'state': {}, 'param_groups': [{'weight_decay': 0.0, 'lr': 5e-05, 'betas': (0.9, 0.999), 'eps': 1e-08, 'correct_bias': True, 'params': [0, 1, 2]}, {'weight_decay': 0.0, 'lr': 5e-05, 'betas': (0.9, 0.999), 'eps': 1e-08, 'correct_bias': True, 'params': [3, 4]}]}
tensor(13.0622) tensor(127.8708) tensor(0.4215) tensor(5.6551) tensor(71.1552)
tensor(13.0623, device='cuda:0') tensor(127.9725, device='cuda:0') tensor(0.4215, device='cuda:0') tensor(5.6550, device='cuda:0') tensor(71.1553, device='cuda:0')
Traceback (most recent call last):
  File "D:/GitHub/OnePunch/OnepunchPrompt_for_new_transformers/Prefix_tune.py", line 129, in <module>
    Prefix_trainer.train()
  File "D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\Prefixtrainer.py", line 272, in train
    out,loss = self.model(**input_)
  File "D:\anaconda\envs\myprompt\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\prompt_models\Prefix_model.py", line 216, in forward
    loss=self.compute_loss(loss_ids=labels, output=output)
  File "D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\prompt_models\Prefix_model.py", line 311, in compute_loss
    shifted_logits, shifted_labels = self.shift_logits_and_labels(logits, loss_ids)
  File "D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\prompt_models\Prefix_model.py", line 276, in shift_logits_and_labels
    shift_logits = logits[..., :-1, :].contiguous()
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 4.00 GiB total capacity; 2.59 GiB already allocated; 45.14 MiB free; 2.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF